language: php

php:
  - 5.5
  - 5.4
  
  
#before_script:
#  - composer install
#  - php vendor/vendors.php
  

script: phpunit --configuration phpunit.xml --coverage-text

notifications:
  email:
    recipients:
      - Danack+travis@BaseReality.com
#    on_success: [always|never|change] # default: change
#    on_failure: [always|never|change] # default: always